// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCMM3NC_qKvbyVoFWPxmMssrsFFRNbEmw',
    appId: '1:518755920303:web:645f13aad1892783cde75a',
    messagingSenderId: '518755920303',
    projectId: 'task-f0cbc',
    authDomain: 'task-f0cbc.firebaseapp.com',
    storageBucket: 'task-f0cbc.appspot.com',
    measurementId: 'G-Y6J5D07CTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLjaW8K3-k91DJ4mQJRPBG2D26jWWQM0',
    appId: '1:518755920303:android:56e9d6f426cf4146cde75a',
    messagingSenderId: '518755920303',
    projectId: 'task-f0cbc',
    storageBucket: 'task-f0cbc.appspot.com',
  );
}
